YetiMunch/Controllers/FoodController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using YetiMunch.Data;
using YetiMunch.Models;
using YetiMunch.Services.Interfaces;

namespace YetiMunch.Controllers
{
    public class FoodController : Controller
    {
        private readonly FoodContext _db;
        private readonly IFoodService _foodService;
        public FoodController(FoodContext db,IFoodService foodService)
        {
            _db = db;
            _foodService = foodService;
        }

        public async Task<IActionResult> ListOfFoods()
        {
            var FoodLists = await _foodService.GetAllFood();
            if (FoodLists == null)
            {
                return BadRequest();
            }

            return View(FoodLists);
        }


        public async Task<IActionResult> AddaFood()
        {
            var hotels =await _db.Hotels
                .Select(h => new HotelDto
                {
                    HotelId = h.HotelId,
                    HotelName = h.HotelName
                })
                .ToListAsync();


            ViewBag.Hotels = hotels ?? new List<HotelDto>();

            return View("AddaFood", new FoodDto());
        }
      




        [HttpPost]
            public async Task<IActionResult> AddFoods([FromForm] FoodDto food)
            {
                if (!ModelState.IsValid)
                {
                    ViewBag.Hotels =await _db.Hotels
                        .Select(h => new HotelDto { HotelId = h.HotelId, HotelName = h.HotelName })
                        .ToListAsync();

                    return View("AddaFood", food); 
                }
            var result = await _foodService.AddNewFood(food);
            if (!result)
            {
                return BadRequest();
            }

            var ListofFoods = await _foodService.GetAllFood();


            return View("ListOfFoods",ListofFoods); 
            }

        [HttpPost]
        public async Task<IActionResult> DeleteFoods([FromForm] int id)
        {
            var result = await _foodService.DeleteFood(id);
            if(!result){
                return BadRequest();
            }
            var foodList = await _foodService.GetAllFood();

            return View("ListOfFoods", foodList);
            
        }

    }
}

YetiMunch/Controllers/HotelController.cs
using Microsoft.AspNetCore.Mvc;
using YetiMunch.Data;
using YetiMunch.Entities;
using YetiMunch.Models;
using YetiMunch.Services.Interfaces;
namespace YetiMunch.Controllers
{
    public class HotelController : Controller
    {
        private readonly FoodContext _db;

        private readonly IHotelService _hotelService;
        public HotelController(FoodContext db,IHotelService hotelService)
        {
            _db = db;
            _hotelService = hotelService;
        }

        [HttpGet]
        public async Task<IActionResult> GetHotels()
        {
            var hotels = await _hotelService.GetAllHotels();
            return View("HotelPage",hotels);
        }
        public IActionResult GotoHotelPage()
        {
            return View("AddHotels");
        }

        [HttpPost]
        public async Task<IActionResult> CreateHotels(Hotel hotel)
        {
            var result = await _hotelService.AddHotel(hotel);
            if (!result)
            {
                return BadRequest();
            }
            var hotelLists = await _hotelService.GetAllHotels();
            if (hotelLists == null)
            {
                return NotFound();
            }

            return View("HotelPage",hotelLists);
            
        }


        [HttpPost]
        public async Task<IActionResult> DeleteHotel([FromForm] int id)
        {
            var result = await _hotelService.RemoveHotel(id);
            if (!result)
            {
                return BadRequest();
            }
            var hotelLists = await _hotelService.GetAllHotels();
            if (hotelLists == null)
            {
                return NotFound();
            }
            return View("HotelPage", hotelLists);
        }

        public async Task<IActionResult> EditHotel([FromForm] int id)
        {
            var hotel = await _hotelService.GetHotelById(id);
            if (hotel == null)
            {
                return BadRequest();
            }

            return View("EditHotel", hotel);
        }


        public async Task<IActionResult> EditHotelPost([FromForm] HotelDto hotel)
        {

            var result = await _hotelService.UpdateHotel(hotel);
            if (!result)
            {
                return BadRequest();
            }

            var hotelList = await _hotelService.GetAllHotels();

            return View("HotelPage", hotelList);
        }
    }
}

YetiMunch/Controllers/OthersController.cs
using Microsoft.AspNetCore.Mvc;
using YetiMunch.Data;
using YetiMunch.Models;
using YetiMunch.Services.Interfaces;

namespace YetiMunch.Controllers
{
    public class OthersController : Controller
    {

        private readonly IUserService _userService;
        private readonly FoodContext _db;

        public OthersController(IUserService userService, FoodContext db)
        {
            _db = db;
            _userService = userService;
        }
        public IActionResult MovetoLoginPage()
        {
            return View("Login");
        }

        [HttpGet]
        public async Task<IActionResult> GetEndUsers()
        {
            var users=await _userService.GetAllUsers();
            return View("EndUser", users);
        }
        
        [HttpPost]
        public async Task<IActionResult> DeleteUser([FromForm] int id)
        {
            var result = await _userService.DeleteUser(id);
            var users = await _userService.GetAllUsers();
            if (!result)
            {
                ViewBag.ErrorMessage("Cannot delete this user!");
                return View("EndUser", users);
            }

            return View("EndUser", users);
        }


        [HttpPost]
        public async Task<IActionResult> EditUser([FromForm]int id)
        {
            var user = await _userService.GetUserById(id);
            if (user == null)
            {
                return NotFound();
            }

            return View("EditPage", user);
        }
        [HttpPost]
        public async Task<IActionResult>  EditPost(UserDTO userDto)
        {
            var result = await _userService.UpdateUser(userDto);

            if (!result)
            {

                return BadRequest();
            }
            var userList = await _userService.GetAllUsers();

            return View("Enduser", userList);
             }

        public IActionResult BackToDashboard()
        {
            return View("Dashboard");
        }
         
        public IActionResult Signout()
        {
            return View("Login");
        }
        public IActionResult BackToRegisterPage()
        {
            return View("Register");
        }
    }
}

YetiMunch/Views/Others/EditPage.cshtml
@model UserDTO

<div class="container">
    <form method="post" asp-controller="Others" asp-action="EditPost">
        <h1>Edit the User</h1>

        <!-- Hidden ID Field -->
        <input type="hidden" asp-for="Id" />

        <div class="container pt-4">
            <div class="col">
                <div class="col-md-6 mb-3">
                    <label asp-for="Username" class="form-label"></label>
                    <input asp-for="Username" class="form-control border-1 rounded" autocomplete="off" />
                    <span asp-validation-for="Username" class="text-danger"></span>
                </div>

                <div class="col-md-6 mb-3">
                    <label asp-for="Email" class="form-label"></label>
                    <input asp-for="Email" class="form-control border-1 rounded" />
                    <span asp-validation-for="Email" class="text-danger"></span>
                </div>

                <div class="col-md-6 pt-2 d-flex justify-content-center align-items-center">
                    <button class="btn btn-dark rounded w-25 fs-5" type="submit">Edit</button>
                </div>
            </div>
        </div>
    </form>
</div>



@section Scripts {
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.19.3/jquery.validate.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validation-unobtrusive/3.2.11/jquery.validate.unobtrusive.min.js"></script>
}

YetiMunch/Views/Others/Enduser.cshtml
@model List<UserDTO>

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Registered Users</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css">
    <style>
        * {
            margin: 0;
            padding: 0;
            box-sizing: border-box;
        }

        html, body {
            height: 100%;
            overflow: hidden;
            display: flex;
            flex-direction: column;
        }
        .sidebar {
            width: 250px;
            height: 100vh;
            background:Darkorange; 
            color: white;
            position: fixed;
           
        }

            .sidebar a {
                display: block;
                color: white;
                padding: 15px;
                text-decoration: none;
                font-size: 18px;
                transition: 0.3s;
            }

                .sidebar a:hover {
                    background: orange;
                }

            .sidebar .logo {
                display: flex;
                flex-direction: column;
                align-items: center;
                font-weight: bold;
                border-bottom: 1px solid white;
            }

                .sidebar .logo .logoImg {
                    height: 140px;
                    width: 140px;
                    margin-right: 20px;
                }
        .main-content {
            margin-left: 250px;
            flex-grow: 1;
            padding: 20px;
            height: 100vh;
            overflow-y: auto;
            display: flex;
            flex-direction: column;
            background-color: antiquewhite;
        }
        .table-container {
            flex-grow: 1;
            overflow-x: auto;
            display: flex;
            flex-direction: column;
            border-radius:10px;
        
           
        }

        .table {
            width: 100%;
            border-collapse: collapse;
            background: white;
            font-size: 18px;
        }

            .table th, .table td {
                text-align: left;
                padding: 16px;
                border-bottom: 1px solid #ddd;

            }

            .table th {
                background: Darkorange;
                color: white;
            }
        .action-buttons {
            display: flex;
            gap: 10px;
        }
      
        .back-btn-container {
           
            text-align: center;
            position: relative;
        }

    </style>
</head>
<body>

    <div class="sidebar">
        <div class="logo">
            <img class="logoImg" src="~/logo.png" />
        </div>
        <a asp-controller="Others" asp-action="BackToDashboard">
            <i class="fa-solid fa-table-columns"></i> Dashboard
        </a>
        <a asp-controller="Others" asp-action="GetEndUsers">
            <i class="fas fa-users"></i> End Users
        </a>
        <a asp-controller="Hotel" asp-action="GetHotels">
            <i class="fas fa-hotel"></i> Hotels
        </a>
        <a asp-controller="Food" asp-action="ListOfFoods">
            <i class="fas fa-utensils"></i> Foods
        </a>
        <a asp-controller="Others" asp-action="Signout">
            <i class="fa-solid fa-right-from-bracket"></i>  Signout
        </a>
    </div>

    <div class="main-content">
        <h1 class="mb-4">Registered Users</h1>

        <div class="table-container">
            <table class="table table-striped">
                <thead>
                    <tr>
                        <th>User ID</th>
                        <th>Username</th>
                        <th>Actions</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var user in Model)
                    {
                        <tr>
                            <td>@user.Id</td>
                            <td>@user.Username</td>
                            <td class="action-buttons">
                                <form method="post" asp-controller="Others" asp-action="EditUser">
                                    <input type="hidden" name="id" value="@user.Id" />
                                    <button class="btn btn-warning btn-sm" type="submit">Edit</button>
                                </form>
                                <form method="post" asp-controller="Others" asp-action="DeleteUser">
                                    <input type="hidden" name="id" value="@user.Id" />
                                    <button class="btn btn-danger btn-sm" type="submit">Delete</button>
                                </form>
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>

        <div class="back-btn-container">
            <form method="get">
               
                <button class="btn btn-dark text-white " asp-controller="Others" asp-action="BackToDashboard">
                    <i class="fa-solid fa-arrow-left"></i>       
                    Back To Dashboard
                </button>
            </form>
        </div>
    </div>

</body>
</html>